### ISSUE TITLE
What are the data sources and the licence?

### ISSUE THREAD

**Issue by giacecco** [openfootball/football.json#1]
In other words, how do I know this really is _open data_ and not just pirated from copyrighted websites? Thanks!

G.

**Comment by geraldb** [comment]
Please post questions to the [opensport forum](http://group.google.com/group/opensport). Thanks. Cheers.

**Comment by giacecco** [comment]
I see you've rejected my improvements to the README without any comments, fair enough, although that just confirms my original concern. I've posted a question on the forum as you suggested. If the attitude the group has is the same as yours, I guess it won't be published :-/ There is no open data without licensing.
