### ISSUE TITLE
Burnley vs. Liverpool has Burnley playing as club 1 both times in the 16/17 season

### ISSUE THREAD

**Issue by abis123** [openfootball/football.json#13]
Not sure if club 1 is always the home team, but if so Burnley appears as the home team both times they play Liverpool in the 16/17 EPL season.

**Comment by geraldb** [comment]
Yes, the first team is the home team. Could you check the soure <https://github.com/openfootball/eng-england/blob/master/2016-17/1-premierleague-i.txt> (gets auto-build) and than an (authorative) premier league source if there's a mismatch/update? Cheers. PS:  Burnley played the first two games at home (not sure - why) - the second against Liverpool.
