### ISSUE TITLE
EPL gameweek updates

### ISSUE THREAD

**Issue by kennyunited** [openfootball/football.json#15]
Hi.

How often is the English Premier League JSON-file updated? 
Just wondering because the value of the results in the json file in gameweek 5 is still "null".
I would love to use this code, but i can't if the code is not updated frequently. 

Thanks in advance.

**Comment by geraldb** [comment]
@kennyunited Please post your question to the [forum / mailing list](http://groups.google.com/group/opensport). Thanks. Cheers.
