### ISSUE TITLE
Score is wrong

### ISSUE THREAD

**Issue by GuigZ-** [openfootball/football.json#21]
https://github.com/opendatajson/football.json/blob/f03f5cf87dad91d359ead88e4ebfef4529944067/2012-13/en.1.json#L94

Hey,

This data is wrong : can you fix it ? 

Source : https://www.premierleague.com/match/7870

**Comment by geraldb** [comment]
Thanks for reporting. See the source -> <https://github.com/openfootball/eng-england/blob/master/2012-13/1-premierleague-i.txt#L13>.  @GuigZ -  Can YOU fix it?  Just change the text file, please, Thanks.

**Comment by GuigZ-** [comment]
I use this data to my website, but when you merge this issue ?

**Comment by geraldb** [comment]
@GuigZ-  Thanks for the update / fix. Merged.  Cheers.

**Comment by GuigZ-** [comment]
When your repo has been updated with my fix ?

**Comment by geraldb** [comment]
It's open source - please, build your own dataset from the source. It gets updated when it gets updated. Cheers.
