### ISSUE TITLE
Leeds's code

### ISSUE THREAD

**Issue by nurgasemetey** [openfootball/football.json#28]
Hello,

Thanks for awesome repo! I am just curious why "Leeds" has null code?

https://github.com/openfootball/football.json/blob/7b18548ec80262fbf855313202279f7a1e624985/2020-21/en.1.clubs.json#L100-L102

**Comment by geraldb** [comment]
Thanks for reporting. Good catch. The source for the English club code is this text / datafile -> <https://github.com/openfootball/england/blob/master/clubs/clubs.props.txt>   You are welcome to add the missing club plus code.   The football.json datasets get auto-updated every 24 hours from the sources.

**Comment by nurgasemetey** [comment]
Thanks for reply! I will try to add the most suitable code for Leeds.
